name: auvnet
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  cloud_firestore: ^5.6.9
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  firebase_auth: ^5.6.0
  firebase_core: ^3.14.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_svg: ^2.1.0
  get_it: ^8.0.3

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/image/

  fonts:
    - family: DM Sans
      fonts:
        - asset: assets/fonts/dm_sans/DMSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/dm_sans/DMSans-Bold.ttf
          weight: 700

    - family: Rubik
      fonts:
        - asset: assets/fonts/rubik/Rubik-Bold.ttf
          weight: 700
        - asset: assets/fonts/rubik/Rubik-Regular.ttf
          weight: 400
        - asset: assets/fonts/rubik/Rubik-Medium.ttf
          weight: 500

    - family: Mulish
      fonts:
        - asset: assets/fonts/mulish/Mulish-Light.ttf
          weight: 300

flutter_assets:
  assets_path: assets/image/
  output_path: lib/core/utils/
  filename: assets.dart
  field_prefix: null
