// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbQmCwJQDB6XV-S3ZSTXxvAEc3fTEsXKc',
    appId: '1:89865151526:web:00cc3429560ad4bfe5b2e7',
    messagingSenderId: '89865151526',
    projectId: 'auvnet-fd412',
    authDomain: 'auvnet-fd412.firebaseapp.com',
    storageBucket: 'auvnet-fd412.firebasestorage.app',
    measurementId: 'G-G2YNYQXW4P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaWi5_hvEYltw0oFWc_6WYJBPXS0lYK7U',
    appId: '1:89865151526:android:560e4b00411c6d1ae5b2e7',
    messagingSenderId: '89865151526',
    projectId: 'auvnet-fd412',
    storageBucket: 'auvnet-fd412.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZKMBEZFCfzPkaH9_ek5FoJxmW6SKn3X8',
    appId: '1:89865151526:ios:6a3267ad81822fc9e5b2e7',
    messagingSenderId: '89865151526',
    projectId: 'auvnet-fd412',
    storageBucket: 'auvnet-fd412.firebasestorage.app',
    iosBundleId: 'com.example.auvnet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZKMBEZFCfzPkaH9_ek5FoJxmW6SKn3X8',
    appId: '1:89865151526:ios:6a3267ad81822fc9e5b2e7',
    messagingSenderId: '89865151526',
    projectId: 'auvnet-fd412',
    storageBucket: 'auvnet-fd412.firebasestorage.app',
    iosBundleId: 'com.example.auvnet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbQmCwJQDB6XV-S3ZSTXxvAEc3fTEsXKc',
    appId: '1:89865151526:web:308bd7abbcd210dee5b2e7',
    messagingSenderId: '89865151526',
    projectId: 'auvnet-fd412',
    authDomain: 'auvnet-fd412.firebaseapp.com',
    storageBucket: 'auvnet-fd412.firebasestorage.app',
    measurementId: 'G-3SZZKJHSY9',
  );
}
